#This is a basic workflow 
name: Deploy to GitHub Pages

#Controls when the action will run
on: 
  push:
    branches:
      -main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout 
       uses: actions/checkout@v2.3.1

      -name: Install and Build # This example project is built using npm
       run: |
        npm install
        npm run build
       env:
        REACT_APP_APOD_API_KEY: ${{ secrets.REACT_APP_APOD_API_KEY }}

      -name: Deploy
       uses: JamesIves/github-pages-deploy-action@4.1.3
       with:
        branch: gh-pages #The branch the action should deploy to.
        folder: build #The folder the action should deploy.